#!/bin/bash
# 🚀 Inventory Management System - QUICK START

# This script helps you start all three services for local development
# Run this to see the commands, or copy them to your terminals

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Inventory Management System - Full Stack Startup             ║"
echo "║  3 Terminals Required (Firebase, Backend, Frontend)           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "TERMINAL 1️⃣: Firebase Emulator (START FIRST!)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1. Install Firebase CLI (one time only):"
echo "   npm install -g firebase-tools"
echo ""
echo "2. Login to Firebase:"
echo "   firebase login"
echo ""
echo "3. Start Emulator (run in project root):"
echo "   firebase emulators:start"
echo ""
echo "   ✅ Firestore Emulator: http://localhost:8080"
echo "   ✅ Auth Emulator: http://localhost:9099"
echo "   ✅ Storage Emulator: http://localhost:9199"
echo "   ✅ Emulator UI: http://localhost:4000"
echo ""
echo "⏸️  Keep this terminal running while testing!"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "TERMINAL 2️⃣: Backend API Server"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1. Navigate to server folder:"
echo "   cd server"
echo ""
echo "2. Copy environment file:"
echo "   cp .env.example .env"
echo ""
echo "3. Install dependencies:"
echo "   npm install"
echo ""
echo "4. Start development server:"
echo "   npm run dev"
echo ""
echo "   ✅ API Server: http://localhost:3000"
echo "   ✅ Swagger Docs: http://localhost:3000/api-docs"
echo "   ✅ Health Check: curl http://localhost:3000/health"
echo ""
echo "⏸️  Keep this terminal running while testing!"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "TERMINAL 3️⃣: Frontend Angular App"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1. Go back to project root (parent of server/):"
echo "   cd .."
echo ""
echo "2. Install dependencies:"
echo "   npm install"
echo ""
echo "3. Start Angular dev server:"
echo "   npm start"
echo ""
echo "   ✅ Frontend App: http://localhost:4200"
echo "   ✅ Login: admin@demo.com / admin123"
echo ""
echo "⏸️  Keep this terminal running while testing!"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "✅ VERIFICATION CHECKS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Once all 3 are running, verify with these URLs:"
echo ""
echo "1. Firebase Emulator UI:"
echo "   http://localhost:4000"
echo ""
echo "2. Backend API (Health Check):"
echo "   curl http://localhost:3000/health"
echo ""
echo "3. API Swagger Documentation:"
echo "   http://localhost:3000/api-docs"
echo ""
echo "4. Frontend Application:"
echo "   http://localhost:4200/login"
echo "   Email: admin@demo.com"
echo "   Password: admin123"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🧪 QUICK API TESTS (Once Backend is Running)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Health Check:"
echo "curl http://localhost:3000/health"
echo ""
echo "Register User:"
echo "curl -X POST http://localhost:3000/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"email\":\"test@example.com\",\"password\":\"Test@123\",\"displayName\":\"Test User\"}'"
echo ""
echo "Login:"
echo "curl -X POST http://localhost:3000/api/auth/login \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"email\":\"admin@demo.com\",\"password\":\"admin123\"}'"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "📚 DOCUMENTATION"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "- README.md - Main setup guide"
echo "- PHASE_1_2_COMPLETE.md - Completion status & what's built"
echo "- FIREBASE_EMULATOR_SETUP.md - Firebase emulator guide"
echo "- server/README.md - Backend API documentation"
echo "- UI_UX_DESIGN.md - Design specifications"
echo "- FIRESTORE_SCHEMA.md - Database structure"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🎯 NEXT STEPS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Once all 3 services are running:"
echo ""
echo "1. Login to frontend with demo credentials"
echo "2. Navigate through Dashboard"
echo "3. Try adding a new product"
echo "4. Search and filter products"
echo "5. Monitor Firestore data in Emulator UI"
echo "6. Check API responses in Network tab"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "🚨 TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Port already in use?"
echo "  Windows: netstat -ano | findstr :3000"
echo "  Mac/Linux: lsof -i :3000"
echo ""
echo "Firebase Emulator won't start?"
echo "  - Check Java: java -version"
echo "  - Update Firebase: npm install -g firebase-tools@latest"
echo ""
echo "Backend can't connect to Firestore?"
echo "  - Verify emulator is running: http://localhost:4000"
echo "  - Check server/.env has correct FIRESTORE_EMULATOR_HOST"
echo ""
echo "Frontend shows errors?"
echo "  - Check console (F12) for error messages"
echo "  - Verify backend is running: curl http://localhost:3000/health"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "✅ You're all set! Follow the steps above and enjoy! 🎉"
echo "═══════════════════════════════════════════════════════════════════"
